adding the inbox messages page and the chatscreen
Joseph-Lartey/N.A.C.K pull request #46
Opened 2024-07-02 23:48 UTC by AlvinBrocke

- added the chatscreen page
- added the inbox-messages page
- edited the navbar to navigate to the messages page
- updated the pubspec file to include the camera function

2024-07-03 11:53 UTC, buzbunny approved these changes

2024-07-03 12:26 UTC, P-Asare requested changes
I think it's good but I think you should make it look a lot more like the UI.

- The header bar (text, notification icon, background color)
- The shape of the search bar (border radius)
- The line between each message bar

2024-07-04 18:23 UTC, kwakuNti approved these changes

2024-07-04 18:27 UTC, kwakuNti commented
it looks good , i have checked and its working just fine

2024-07-06 17:32 UTC, P-Asare approved these changes
I made a few changes to the UI.

- Height of the search bar
- Separator between chats

Good job on the pages though. 💪

2024-07-06 17:33 UTC, merged